In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

%matplotlib inline

In [7]:
file_pathS = Path("../Resources/sentiment.csv")
df_sentiment = pd.read_csv(file_pathS, infer_datetime_format = True, parse_dates = True, index_col = "minute")
df_sentiment.sort_index(inplace=True)

In [8]:
df_sentiment

                     sentiment_vader  sentiment_rnn
minute
2020-09-29 03:46:00         0.000000       1.000000
2021-01-28 09:08:00         0.230769       0.384615
2021-01-28 09:09:00         0.625000       0.500000
2021-01-28 09:10:00         0.200000       0.200000
2021-01-28 09:11:00         0.166667       0.333333
...                              ...            ...
2021-04-05 15:22:00         1.000000       1.000000
2021-04-05 16:26:00         0.000000       1.000000
2021-04-05 16:28:00         0.000000       0.000000
2021-04-05 16:35:00         0.000000       0.000000
2021-04-05 16:57:00         0.000000       1.000000

[17823 rows x 2 columns]

In [9]:
file_pathD = Path("../Resources/all_data_csv.csv")
df_data = pd.read_csv(file_pathD, infer_datetime_format = True, parse_dates = True, index_col = "date_time")
df_data.sort_index(inplace=True)

In [10]:
df_data

,gme_px,gme_vol,amc_px,amc_vol,bb_px,bb_vol,bbby_px,bbby_vol,nok_px,nok_vol,spy_px,spy_vol,us2y10y,vix,usdjpy
date_time,,,,,,,,,,,,,,,
2021-01-20 09:30:00,37.100,462532,3.2084,5178457,13.2800,2912445,25.560,69679,4.1600,757452,380.780,473443,96.383,22.24,103.77
2021-01-20 09:31:00,37.000,145537,3.2300,1995504,13.1800,1508715,25.390,41014,4.1550,90491,380.810,192309,96.383,22.24,103.77
2021-01-20 09:32:00,36.885,127614,3.2300,1596001,13.3787,1181414,25.350,18128,4.1589,60009,380.910,191584,96.383,22.51,103.76
2021-01-20 09:33:00,37.180,103450,3.1850,1751775,13.4699,2118881,25.440,21749,4.1680,309279,380.840,117054,96.383,22.51,103.76
2021-01-20 09:34:00,37.925,194768,3.1899,1072650,13.3600,1265008,25.580,26630,4.1600,68592,380.950,109180,96.554,22.47,103.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-31 15:55:00,191.980,15778,10.1600,101166,8.4250,48060,29.125,28164,3.9650,67617,396.345,1730134,157.142,19.01,110.73
2021-03-31 15:56:00,191.960,13801,10.2199,308278,8.4250,111643,29.120,28940,3.9650,328314,396.520,1484195,156.964,18.99,110.73
2021-03-31 15:57:00,191.951,21260,10.2250,165293,8.4200,86947,29.175,24932,3.9650,82452,396.520,1657290,157.142,18.97,110.73
2021-03-31 15:58:00,191.130,20765,10.2100,169608,8.4250,106312,29.180,37675,3.9700,87043,396.830,2252087,157.142,18.95,110.72
2021-03-31 15:59:00,190.010,58711,10.2099,183929,8.4199,216901,29.170,82624,3.9650,248857,396.330,6944712,157.499,18.96,110.73